source :rubygems

gem "mixlib-cli", "~> 1.2.2", :require => "mixlib/cli"
gem "mixlib-log", "~> 1.3.0", :require => "mixlib/log"
gem "chef", "~> 0.10.8"
gem "ffi-rzmq", "~> 0.9.3"
gem "yajl-ruby", "~> 1.1.0", :require => "yajl"
#gem "uuid", "~> 2.3.5"
gem "em-zeromq", "~> 0.3.0"
gem "mixlib-authentication", "1.1.5", :git => "git://github.com/opscode/mixlib-authentication.git", :branch => 'f3cd8b31e04aac87f82bb4ae1de6a2bf0ab49401'

group :test do
  gem "rspec"
end
