source 'https://rubygems.org'

gem "omnibus", :git => "https://github.com/chef/omnibus.git"
gem "omnibus-software", :git => "https://github.com/chef/omnibus-software.git"

group :development do
  gem 'test-kitchen'
  gem 'kitchen-vagrant'
  gem 'berkshelf'
end
