source 'https://rubygems.org'

gem 'omnibus', github: 'chef/omnibus'
gem 'omnibus-software', github: 'chef/omnibus-software'
gem 'license_scout', git: 'https://github.com/chef/license_scout'

group :development do
  gem 'test-kitchen'
  gem 'kitchen-vagrant'
  gem 'berkshelf'
end
