source 'https://rubygems.org'

gem "omnibus", git: "https://github.com/chef/omnibus", branch: "master"
gem "omnibus-software", git: "https://github.com/chef/omnibus-software", branch: "master"
gem "artifactory"

group :development do
  gem 'test-kitchen'
  gem 'kitchen-vagrant'
  gem 'berkshelf'
end
