#!/bin/sh

download_dep() {
    if [ -d ../$1 ]; then
	echo "Dependency $1 exists. Skipping..."
    else
	echo "Cloning dependency $1..."
	git clone git@github.com:opscode/$1.git ../$1
    fi
}

build_deb() {
    ./bin/vagrant omnibus build $1 opscode-push-jobs-server
    ./bin/vagrant destroy
}

download_dep "omnibus-software"
download_dep "omnibus-ruby"

if [ ! -f omnibus.rb ]; then
    echo "Using example omnibus configuration..."
    cp omnibus.rb.example omnibus.rb
fi

echo "Running bundle install..."
bundle install --binstubs

echo "Building omnibus package for $1. Please wait..."
build_deb $1
