source "https://rubygems.org"

# Pinned to the same version shipped in the current pushy client
gem "chef", "14.10.9"
gem "ohai", "~> 14.8"
gem "rake"

gemspec

gem 'rest-client', :git => 'git://github.com/opscode/rest-client.git'
gem 'oc-chef-pedant', :git => "https://github.com/chef/chef-server.git"
gem 'opscode-pushy-client', :git => "https://github.com/chef/opscode-pushy-client.git"
