source "https://rubygems.org"

gem "chef"

gemspec

gem 'rest-client', :git => 'git://github.com/opscode/rest-client.git'
gem 'oc-chef-pedant', :git => "https://github.com/chef/chef-server.git"
gem 'opscode-pushy-client', :git => "https://github.com/chef/opscode-pushy-client.git", :branch => "praj/bundler_update"
